# Textos a mostrar, hay una variable por cada pantalla. El caracter "#"" se usa para indicar cambio de página.
guion = [
    "HIJO MIO... HAN SIDO LARGOS AÑOS\nDE DURO ENTRENAMIENTO, AHORA\nESCUCHA LA HISTORIA QUE VOY A\nNARRARTE. LUEGO, DE TI DEPENDERÁ#" \
    "MI FUTURO... Y EL DE LO QUE\nQUE QUEDA DE HUMANIDAD.#",

    "HACE MUCHOS AÑOS EN ESTE MALDITO\nPLANETA EXISTIÓ UNA GRAN CULTURA\nNUESTROS ANTEPASADOS VIVÍAN EN\nGIGANTESCAS CONSTRUCCIONES QUE#" \
    "LLEGABAN AL CIELO, PERO LA\nCODICIA DE ESTOS LES CONDUJO A\nSU PROPIA EXTINCIÓN.#",

    "GIGANTESCOS ÁRBOLES DE FUEGO,\nACABARON CON LA BRILLANTE\nCIVILIZACIÓN. LOS GRANDES ÁRBOLES\nTRANSFORMARON EN CENIZAS#" \
    "CONSTRUCCIONES, HOMBRES Y\nANIMALES POR IGUAL#",

    "SOLO UNOS POCOS SOBREVIVIERON,\nAQUELLOS ELEGIDOS EMPRENDIERON\nUNA DIFÍCIL TAREA E INTENTARON\nVOLVER A SER COMO ERAN, PERO...#" \
    "JAMAS LO CONSIGUIERON.\nLAS EPIDEMIAS SE SUCEDIERON Y\nDIEZMARON AUN MÁS A LA YA AZOTADA\nCIVILIZACIÓN#",

    "LOS REMOTOS Y OLVIDADOS TIEMPOS\nDE BRUJOS, DRAGONES Y HECHIZEROS\nREGRESARON. FUE ENTONCES CUANDO\nAPARECIÓN EL PRIMER -DARK-#" \
    "ESTE NO TARDÓ EN RECLUTAR Y\nADIESTRAR FUERTES Y MALÉVOLOS\nSERES.#",

    "EL Y SU TROPA SAQUEARON, MATARON\nY VIOLARON A LOS INDEFENSOS\nHABITANTES DE LOS POBLADOS\nPOR DONDE PASABAN .#" \
    "PRIMERO FUERON LAS ALDEAS DE LA\nCOSTA Y DESPUÉS LAS DEL INTERIOR\nTODOS ERAN SOMETIDOS BAJO SU\nCRUEL Y SANGRIENTA MIRADA.#",

    "KAMUIR, EL SEGUNDO -DARK-, NO SE\nHIZO ESPERAR, TRAS LA MUERTE DE\nSU PADRE SAQUEÓ NUESTRO POBLADO\nY SEGÓ LA VIDAD DE MI FAMILIA.#" \
    "CON FRIA SONRISA LENTAMENTE BAJÓ\nSU CABEZA Y ME MIRÓ, YO PORTABA\nEN MIS BRAZOS EL LIBRO MÍSTICO\nEL CONTENIDO DE ESE LIBRO LO ERA#" \
    "TODO PARA MI. ERA MI PROTECTOR\nCONTRA LAS FUERZAS OCULTAS DE\nLAS TINIEBLAS. PUDE ESCAPAR DE\nAQUEL INFIERNO.#",

    "ESTUVE AL BORDE DE LA MUERTE EN\nVARIAS OCASIONES, PERO PUDE\nALCANZAR UN FOCO DE CIVILIZACIÓN\nALEJADO DE LA DESOLACIÓN.#" \
    "PASARON LOS AÑOS Y CUANDO TODO\nERA RECORDADO COMO UNA LEJANA\nPESADILLA, KAMUIR REGRESÓ CON\nSU ODIO HACIA TODO LO VIVO.#",

    "POR SEGUNDA VEZ DESTRUYÓ TODO\nAQUELLO POR LO QUE YO HABÍA\nLUCHADO, MI FAMILIA Y MI LIBRO\nDEL CUAL SE APODERÓ#",

    "FUE SOBRE LA TUMBA DE TU MADRE\nDONDE YO JURÉ VENGANZA, Y AHORA\nTÚ SERÁS EL ENCARGADO DE\nLLEVARLA A CABO.#"
]