;******************************************************************
;*** TRITON SOFTWARE **** SAGA DARK, FASE DRAGON ******************
;****************************************************************** 
;*** GRAFICO DE LUNA, DIMENSIONES 9 X 4 CARACTERES (9X32 BYTES) ***
;****************************************************************** 

        ORG     49373
                                 
;****************************************************************************
;                      WARNING: DO NOT EDIT THIS SECTION!                    
;      This section gets automatically generated by the Resource Editor      
;   And any data here will get overwritten, when the resources are updated   
;****************************************************************************
; [RESOURCES SECTION                                                         
; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Tile\GR_LUNA><Data:ScanlinesRowColumn:XChar:YChar:MaskBeforePixels:MaskInvert>]
; Name   : GR_LUNA
; Size   : 72x32
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
GR_LUNA:
; pixels and mask bit pairs
defb   0,   0,   0,   0,   0,   0,   0,   0,   0
defb   0,   0,   0,   0,   0,   0,   0,   0,   0
defb   0,   0,   0,   0,   0,   0,   0,   2, 168
defb   0,   0,   0,   0,  31, 192,   0,   0,   0
defb   0,   0,   0,   0, 127, 240,   3, 224,   0
defb   0,   0,   0,   1, 255, 252,  21,  80,   0
defb   0,   0,   0,   3, 255, 234, 170, 170, 224
defb   0,   0,   0,   7, 255,  85,  31,  21,  84
defb   0,   0, 255,  15, 255, 255, 128,   0,   0
defb   0,  11,  80,  31, 255, 255, 128,   0,   0
defb   0,  20, 170, 170, 255, 255, 192,   0,   0
defb   5, 175, 192,  85,  85, 255, 192,   0,   0
defb   0, 240,   0,  42, 170, 191, 224,   0,   0
defb 181,   0,   0,  63, 255, 255, 226, 160,   0
defb  10, 248,   0,  63, 255, 255, 229,  84,   0
defb   0,   6,   0,  63, 255, 255, 170,   0,   0
defb   0,   1,  85,  95, 255, 255,  80,   0,   0
defb   0,  20, 128,  63, 255, 255, 239, 193, 192
defb   0, 107,  26,  63, 255, 255, 214, 162, 176
defb   0,   0,   5,   3, 255, 254, 175,  85, 108
defb 108, 192, 158, 252,  61,  85,  95, 231, 215
defb   0,   0,   0,   2, 143, 234, 172,   3, 234
defb   0,   0,   0,  15, 255, 255, 190,   4, 189
defb   0,   0,   0,   7, 195, 255,  95, 121,  14
defb   0,   0,   0,   3, 181, 170, 171, 206,   7
defb   0,   0,   0,  10,  26, 125,  87, 186, 165
defb   0,   0,   0,  21, 125,  50, 170, 224,  26
defb   0,   0,   0, 168, 223, 197,  85, 181,  79
defb   0,   0,  21,  85,  42, 162, 170,   0,   0
defb   0,   0,   0,   2, 222, 221,  88,   0,   0
defb   0,   0,   0,   0,   0,   0,   0,   0,   0
defb   0,   0,   0,   0,   0,   0,   0,   0,   0
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Tile\GR_LUNA>]              

; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Tile>]                      

; ]RESOURCES SECTION                                                         
